### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by jayudhandha** [childsish/dynamic-yaml#22]
Hi,

I'm trying to parse below yaml and getting `RecursionError: maximum recursion depth exceeded in comparison`

```
Derived Insights:
  transaction_value_segment:
    id: 4
    type: multiselect
    name: transaction_value_segment
    label: transaction segment
    options:
    - name: IFQ
      value: IFQ
    - name: Premium
      value: Premium
    - name: Lapsed
      value: Lapsed
    value:
    - IFQ
    - Premium
```
I think it's related to arrays in yaml, without that it's working fine. Any suggestions how to fix this?

Thanks,
Jayesh
