### ISSUE TITLE
Problems with recursive=True

### ISSUE THREAD

**Issue by MTDzi** [childsish/dynamic-yaml#5]
I have the following .yml file:
```
prefix: /opt/ml

input_path: '{prefix}/input'
model_path: '{prefix}/model'
output_path: '{prefix}/output'

failure_path: '{output_path}/failure'

# Training
training:
  training_data_path: '{input_path}/data/training'
#  mia_path: '{training_data_path}/MiaPds.json'
  metro_path: '{training.training_data_path}/MetroPds.json'
  test_size: 0.8
  random_seed: 42
```
which I'm reading in using the following snippet:
```
with open(CONFIG_PATH) as inp:
    config = dynamic_yaml.load(inp, recursive=True)
```
if I enter here with a debugger and type in just `config` I see:
```
{'prefix': '/opt/ml',
 'input_path': '/opt/ml/input',
 'model_path': '/opt/ml/model',
 'output_path': '/opt/ml/output',
 'failure_path': '/opt/ml/output/failure',
 'training': {'training_data_path': '/opt/ml/input/data/training',
  'metro_path': '/opt/ml/input/data/training/MetroPds.json',
  'test_size': 0.8,
  'random_seed': 42}}
```
which is awesome, that was my intention.

But if I type in `print(config)` I get:
```
{'prefix': '/opt/ml', 'input_path': '{prefix}/input', 'model_path': '{prefix}/model', 'output_path': '{prefix}/output', 'failure_path': '{output_path}/failure', 'training': {'training_data_path': '{input_path}/data/training', 'metro_path': '{training.training_data_path}/MetroPds.json', 'test_size': 0.8, 'random_seed': 42}}
```
(I know it's long, I just wanted to copy it as-is.)

And now the fun part:
* if I ask for `print(config['training']['metro_path'])` I get what I expected: `/opt/ml/input/data/training/MetroPds.json`
* but when I pass on `config` to a function `train` like so:
   ```
        train(**config['training'])
        # where the train function's signature is:
        # def train(metro_path, def train(metro_path, training_data_path, test_size, random_seed, **kwargs):
   ```
    within that function I ask for `metro_path` I get:
    ```
        '{training.training_data_path}/MetroPds.json'
    ```
     which is not what I was expecting :\

I would appreciate any help / hints / suggestions / whatever ;)
